# Generated by Django 5.1.7 on 2025-04-24 08:30

import django.core.validators
import django.db.models.deletion
import mptt.fields
import uuid_extensions
from django.db import migrations, models

import online_shop.products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('product', 'Product Wide'), ('order', 'Order Wide'), ('personal', 'Personal')], max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('value', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Value should be 1 atleast'), django.core.validators.MaxValueValidator(100, 'Discount value cant be more than 100')])),
                ('start_at', models.DateTimeField()),
                ('expired_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(blank=True, primary_key=True, serialize=False)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='products.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid_extensions.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, verbose_name='product name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(max_length=5)),
                ('cover', models.ImageField(upload_to=online_shop.products.models.product_image_path)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.discount')),
            ],
        ),
    ]
