# Generated by Django 5.1.7 on 2025-04-29 10:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='_price',
        ),
        migrations.AlterField(
            model_name='product',
            name='_price',
            field=models.DecimalField(db_column='price', decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
