# Generated by Django 5.1.7 on 2025-04-24 08:25

import django.db.models.deletion
import uuid_extensions.uuid7
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.CharField(default=uuid_extensions.uuid7, max_length=128, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('cdek', 'Cdek'), ('russian_mail', 'Russianpost')], max_length=128)),
                ('address', models.TextField()),
                ('receiver', models.TextField()),
                ('receiver_phone', models.CharField(max_length=64)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
